[phases.setup]
nixPkgs = ["nodejs", "pnpm"]

[phases.install]
cmds = ["pnpm install --no-frozen-lockfile"]

[phases.build]
cmds = ["pnpm build:shared", "pnpm --dir platform/apps/web build"]

[start]
cmd = "cd platform/apps/web && pnpm start"
